From r-base

MAINTAINER Patrik

RUN apt-get update
RUN apt-get -y install libpq-dev

RUN R -e 'install.packages("plumber")'
RUN R -e 'install.packages("RPostgreSQL")'

ADD database.r .

EXPOSE 8000
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb(commandArgs()[4]); pr$run(port=8000)"]

CMD ["database.r"]

